### ISSUE TITLE
关于AdminLogin插件无法使用

### ISSUE THREAD

**Issue by moxiaowk** [v03413/Typecho_Plugins#3]
![image](https://user-images.githubusercontent.com/62387130/171772997-492ac1f2-f417-4e49-9f68-6ead8dde8258.png)
![image](https://user-images.githubusercontent.com/62387130/171773025-46a03236-ce77-46fe-928d-0ea4b3edd109.png)
![image](https://user-images.githubusercontent.com/62387130/171773050-d1a7dd5f-ace1-4001-a6c8-59861060786f.png)
大佬，typecho的 AdminLogin插件用不了，一是扫了没反应，二是显示未知错误，刷新也没有用

**Comment by v03413** [comment]
服务器是大陆还是海外的

**Comment by moxiaowk** [comment]
大陆的

**Comment by v03413** [comment]
已修复 https://github.com/v03413/Typecho_Plugins/commit/63c1bc4233d5a89a319e2319e896a348da371d30
